### PR TITLE
Fix gen_migration :overwrite

### PR DESCRIPTION
**Pull request by leandrocp**
Fix a typo and _try_ to add a test although I'm not sure that test is correctly handling `igniter.assigns[:test_files]`.

### CODE REVIEW

**Comment by zachdaniel** [comment]
What do you meant that it's not correctly handling `:test_files`? I'll maybe see more when the tests run.

**Comment by leandrocp** [comment]
I had a `apply_igniter!/1` after the first `gen_migration` because I assume that was necessary to actually create the file and then assert that `:overwrite` works properly but seems like that removes the file from `:test_files` so I'm not sure the test is correct, but I guess it's fine.

**Comment by zachdaniel** [comment]
Hmm...yeah thats not right. I'll look into it

**Comment by zachdaniel** [comment]
It looks like it's in test_files to me 🤔

**Comment by zachdaniel** [comment]
Looks like its working as intended to me

**Comment by leandrocp** [comment]
Well then never mind. I was doing some tests and might have changed something unexpected. Still learning how the internal parts work :)

**Pull request merged**
