### PR TITLE
improvement: support "notices"

### PR DESCRIPTION
**Pull request by ibarakaiev**
### Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Features include unit/acceptance tests

This PR adds the support for "notices", which is the programmable output that will be printed once an Igniter runs successfully. They are printed in green, and are intended for things like "next steps" and such.

UPD: this PR also pretties up the output by surrounding relevant warning and notice sections with blank lines where necessary. The old "Notices" has also been renamed to "Warnings".

### CODE REVIEW

**Comment by zachdaniel** [comment]
There are places where you edit a file that you can return `{:warning, ...}` and `{:error, ...}`, we should make those support `{:notice, ...}` as well. Otherwise, LGTM!

**Comment by ibarakaiev** [comment]
What should the return format be? `{:notice, {zipper, notice}}` or something like that? For warnings and errors, a zipper is not modified, but for notices it is. I almost feel like notices should only ever be added for things like "next steps" or "please read the README here: ..." so I'm not sure what would be a use case for returning a notice tuple like that 🤔

**Comment by zachdaniel** [comment]
🤔 yeah, okay good point. Lets leave it :) So this is ready to go?

**Comment by ibarakaiev** [comment]
Yeah, I think so!

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
